package ClientAndServer;

/**
* ClientAndServer/HelloWorldHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 26 March 2020 17:15:50 o'clock GMT
*/

public final class HelloWorldHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld value = null;

  public HelloWorldHolder ()
  {
  }

  public HelloWorldHolder (HelloWorld initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorldHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorldHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorldHelper.type ();
  }

}
