package ClientAndServer;


/**
* ClientAndServer/MonitoringSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from relay.idl
* Friday, 27 March 2020 19:21:11 o'clock GMT
*/

public interface MonitoringSystemOperations 
{
  String alertMessage ();
} // interface MonitoringSystemOperations
