package ClientAndServer;


/**
* ClientAndServer/Relay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 26 March 2020 17:15:50 o'clock GMT
*/

public interface Relay extends RelayOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Relay
