package ClientAndServer;

/**
* ClientAndServer/RelayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 26 March 2020 17:15:50 o'clock GMT
*/

public final class RelayHolder implements org.omg.CORBA.portable.Streamable
{
  public Relay value = null;

  public RelayHolder ()
  {
  }

  public RelayHolder (Relay initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RelayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RelayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RelayHelper.type ();
  }

}
