package ClientAndServer;


/**
* ClientAndServer/RelayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 26 March 2020 17:15:50 o'clock GMT
*/

public interface RelayOperations 
{
  String fetch_message();
} // interface RelayOperations
