package AssignmentTwo;


/**
* AssignmentTwo/_LocalServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public class _LocalServerStub extends org.omg.CORBA.portable.ObjectImpl implements AssignmentTwo.LocalServer
{

  public AssignmentTwo.StationDetails[] connected_stations ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_connected_stations", true);
                $in = _invoke ($out);
                AssignmentTwo.StationDetails $result[] = AssignmentTwo.stationListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connected_stations (        );
            } finally {
                _releaseReply ($in);
            }
  } // connected_stations

  public AssignmentTwo.ServerDetails get_server_details ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_server_details", true);
                $in = _invoke ($out);
                AssignmentTwo.ServerDetails $result = AssignmentTwo.ServerDetailsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_server_details (        );
            } finally {
                _releaseReply ($in);
            }
  } // get_server_details

  public void set_details (AssignmentTwo.ServerDetails details)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("set_details", true);
                AssignmentTwo.ServerDetailsHelper.write ($out, details);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                set_details (details        );
            } finally {
                _releaseReply ($in);
            }
  } // set_details

  public AssignmentTwo.Reading[] all_readings ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("all_readings", true);
                $in = _invoke ($out);
                AssignmentTwo.Reading $result[] = AssignmentTwo.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return all_readings (        );
            } finally {
                _releaseReply ($in);
            }
  } // all_readings

  public AssignmentTwo.Reading[] get_readings (String station_name)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_readings", true);
                $out.write_string (station_name);
                $in = _invoke ($out);
                AssignmentTwo.Reading $result[] = AssignmentTwo.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_readings (station_name        );
            } finally {
                _releaseReply ($in);
            }
  } // get_readings

  public AssignmentTwo.Reading[] get_current_readings ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_current_readings", true);
                $in = _invoke ($out);
                AssignmentTwo.Reading $result[] = AssignmentTwo.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_current_readings (        );
            } finally {
                _releaseReply ($in);
            }
  } // get_current_readings

  public AssignmentTwo.Reading[] alerts ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("alerts", true);
                $in = _invoke ($out);
                AssignmentTwo.Reading $result[] = AssignmentTwo.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return alerts (        );
            } finally {
                _releaseReply ($in);
            }
  } // alerts

  public void register_monitoring_station (AssignmentTwo.StationDetails details)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("register_monitoring_station", true);
                AssignmentTwo.StationDetailsHelper.write ($out, details);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                register_monitoring_station (details        );
            } finally {
                _releaseReply ($in);
            }
  } // register_monitoring_station

  public void send_alert (AssignmentTwo.Reading reading)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("send_alert", true);
                AssignmentTwo.ReadingHelper.write ($out, reading);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                send_alert (reading        );
            } finally {
                _releaseReply ($in);
            }
  } // send_alert

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AssignmentTwo/LocalServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LocalServerStub
