package AssignmentTwo;

/**
* AssignmentTwo/AgencyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Tuesday, 31 March 2020 19:26:32 o'clock BST
*/

public final class AgencyHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.Agency value = null;

  public AgencyHolder ()
  {
  }

  public AgencyHolder (AssignmentTwo.Agency initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.AgencyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.AgencyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.AgencyHelper.type ();
  }

}
