package AssignmentTwo;

/**
* AssignmentTwo/AlertHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Tuesday, 31 March 2020 19:26:32 o'clock BST
*/

public final class AlertHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.Alert value = null;

  public AlertHolder ()
  {
  }

  public AlertHolder (AssignmentTwo.Alert initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.AlertHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.AlertHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.AlertHelper.type ();
  }

}
