package AssignmentTwo;


/**
* AssignmentTwo/Alert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class Alert implements org.omg.CORBA.portable.IDLEntity
{
  public String server_name = null;
  public AssignmentTwo.Reading alert_readings[] = null;

  public Alert ()
  {
  } // ctor

  public Alert (String _server_name, AssignmentTwo.Reading[] _alert_readings)
  {
    server_name = _server_name;
    alert_readings = _alert_readings;
  } // ctor

} // class Alert
