package AssignmentTwo;


/**
* AssignmentTwo/Alert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public final class Alert implements org.omg.CORBA.portable.IDLEntity
{
  public String server_name = null;
  public AssignmentTwo.Reading alerts[] = null;

  public Alert ()
  {
  } // ctor

  public Alert (String _server_name, AssignmentTwo.Reading[] _alerts)
  {
    server_name = _server_name;
    alerts = _alerts;
  } // ctor

} // class Alert
