package AssignmentTwo;


/**
* AssignmentTwo/LocalServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public interface LocalServerOperations 
{
  AssignmentTwo.StationDetails[] connected_stations ();
  AssignmentTwo.ServerDetails get_server_details ();
  void set_details (AssignmentTwo.ServerDetails details);
  AssignmentTwo.Reading[] all_readings ();
  AssignmentTwo.Reading[] get_readings (String station_name);
  AssignmentTwo.Reading[] get_current_readings ();
  AssignmentTwo.Reading[] alerts ();
  void register_monitoring_station (AssignmentTwo.StationDetails details);
  void send_alert (AssignmentTwo.Reading reading);
} // interface LocalServerOperations
