package AssignmentTwo;

/**
* AssignmentTwo/LocalServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class LocalServerHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.LocalServer value = null;

  public LocalServerHolder ()
  {
  }

  public LocalServerHolder (AssignmentTwo.LocalServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.LocalServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.LocalServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.LocalServerHelper.type ();
  }

}
