package AssignmentTwo;

/**
* AssignmentTwo/MonitoringCentreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class MonitoringCentreHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.MonitoringCentre value = null;

  public MonitoringCentreHolder ()
  {
  }

  public MonitoringCentreHolder (AssignmentTwo.MonitoringCentre initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.MonitoringCentreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.MonitoringCentreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.MonitoringCentreHelper.type ();
  }

}
