package AssignmentTwo;


/**
* AssignmentTwo/MonitoringCentre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public interface MonitoringCentre extends MonitoringCentreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MonitoringCentre
