package AssignmentTwo;


/**
* AssignmentTwo/MonitoringStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public interface MonitoringStationOperations 
{
  AssignmentTwo.Reading reading ();
  AssignmentTwo.Reading[] reading_log ();
  void get_reading ();
  void set_details (AssignmentTwo.StationDetails details);
  AssignmentTwo.StationDetails get_details ();
  void activate ();
  void deactivate ();
  void reset ();
} // interface MonitoringStationOperations
