package AssignmentTwo;


/**
* AssignmentTwo/MonitoringCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public abstract class MonitoringCentrePOA extends org.omg.PortableServer.Servant
 implements AssignmentTwo.MonitoringCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("all_readings", new java.lang.Integer (0));
    _methods.put ("get_readings", new java.lang.Integer (1));
    _methods.put ("_get_connected_servers", new java.lang.Integer (2));
    _methods.put ("register_local_server", new java.lang.Integer (3));
    _methods.put ("unregister_local_server", new java.lang.Integer (4));
    _methods.put ("send_alert", new java.lang.Integer (5));
    _methods.put ("register_agency", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AssignmentTwo/MonitoringCentre/all_readings
       {
         AssignmentTwo.Reading $result[] = null;
         $result = this.all_readings ();
         out = $rh.createReply();
         AssignmentTwo.readingListHelper.write (out, $result);
         break;
       }

       case 1:  // AssignmentTwo/MonitoringCentre/get_readings
       {
         String server_name = in.read_string ();
         AssignmentTwo.Reading $result[] = null;
         $result = this.get_readings (server_name);
         out = $rh.createReply();
         AssignmentTwo.readingListHelper.write (out, $result);
         break;
       }

       case 2:  // AssignmentTwo/MonitoringCentre/_get_connected_servers
       {
         AssignmentTwo.ServerDetails $result[] = null;
         $result = this.connected_servers ();
         out = $rh.createReply();
         AssignmentTwo.serverListHelper.write (out, $result);
         break;
       }

       case 3:  // AssignmentTwo/MonitoringCentre/register_local_server
       {
         AssignmentTwo.ServerDetails info = AssignmentTwo.ServerDetailsHelper.read (in);
         this.register_local_server (info);
         out = $rh.createReply();
         break;
       }

       case 4:  // AssignmentTwo/MonitoringCentre/unregister_local_server
       {
         AssignmentTwo.ServerDetails info = AssignmentTwo.ServerDetailsHelper.read (in);
         this.unregister_local_server (info);
         out = $rh.createReply();
         break;
       }

       case 5:  // AssignmentTwo/MonitoringCentre/send_alert
       {
         AssignmentTwo.Alert alert = AssignmentTwo.AlertHelper.read (in);
         this.send_alert (alert);
         out = $rh.createReply();
         break;
       }

       case 6:  // AssignmentTwo/MonitoringCentre/register_agency
       {
         AssignmentTwo.Agency agency = AssignmentTwo.AgencyHelper.read (in);
         this.register_agency (agency);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AssignmentTwo/MonitoringCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MonitoringCentre _this() 
  {
    return MonitoringCentreHelper.narrow(
    super._this_object());
  }

  public MonitoringCentre _this(org.omg.CORBA.ORB orb) 
  {
    return MonitoringCentreHelper.narrow(
    super._this_object(orb));
  }


} // class MonitoringCentrePOA
