package AssignmentTwo;


/**
* AssignmentTwo/MonitoringCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public interface MonitoringCentreOperations 
{
  AssignmentTwo.Reading[] all_readings ();
  AssignmentTwo.Reading[] get_readings (String server_name);
  AssignmentTwo.ServerDetails[] connected_servers ();
  void register_local_server (AssignmentTwo.ServerDetails info);
  void unregister_local_server (AssignmentTwo.ServerDetails info);
  void send_alert (AssignmentTwo.Alert alert);
  void register_agency (AssignmentTwo.Agency agency);
} // interface MonitoringCentreOperations
