package AssignmentTwo;


/**
* AssignmentTwo/MonitoringStationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Tuesday, 31 March 2020 19:26:32 o'clock BST
*/

public abstract class MonitoringStationPOA extends org.omg.PortableServer.Servant
 implements AssignmentTwo.MonitoringStationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("reading", new java.lang.Integer (0));
    _methods.put ("_get_reading_log", new java.lang.Integer (1));
    _methods.put ("take_reading", new java.lang.Integer (2));
    _methods.put ("set_info", new java.lang.Integer (3));
    _methods.put ("get_info", new java.lang.Integer (4));
    _methods.put ("activate", new java.lang.Integer (5));
    _methods.put ("deactivate", new java.lang.Integer (6));
    _methods.put ("reset", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AssignmentTwo/MonitoringStation/reading
       {
         AssignmentTwo.Reading $result = null;
         $result = this.reading ();
         out = $rh.createReply();
         AssignmentTwo.ReadingHelper.write (out, $result);
         break;
       }

       case 1:  // AssignmentTwo/MonitoringStation/_get_reading_log
       {
         AssignmentTwo.Reading $result[] = null;
         $result = this.reading_log ();
         out = $rh.createReply();
         AssignmentTwo.readingListHelper.write (out, $result);
         break;
       }

       case 2:  // AssignmentTwo/MonitoringStation/take_reading
       {
         this.take_reading ();
         out = $rh.createReply();
         break;
       }

       case 3:  // AssignmentTwo/MonitoringStation/set_info
       {
         AssignmentTwo.StationDetails info = AssignmentTwo.StationDetailsHelper.read (in);
         this.set_info (info);
         out = $rh.createReply();
         break;
       }

       case 4:  // AssignmentTwo/MonitoringStation/get_info
       {
         AssignmentTwo.StationDetails $result = null;
         $result = this.get_info ();
         out = $rh.createReply();
         AssignmentTwo.StationDetailsHelper.write (out, $result);
         break;
       }

       case 5:  // AssignmentTwo/MonitoringStation/activate
       {
         this.activate ();
         out = $rh.createReply();
         break;
       }

       case 6:  // AssignmentTwo/MonitoringStation/deactivate
       {
         this.deactivate ();
         out = $rh.createReply();
         break;
       }

       case 7:  // AssignmentTwo/MonitoringStation/reset
       {
         this.reset ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AssignmentTwo/MonitoringStation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MonitoringStation _this() 
  {
    return MonitoringStationHelper.narrow(
    super._this_object());
  }

  public MonitoringStation _this(org.omg.CORBA.ORB orb) 
  {
    return MonitoringStationHelper.narrow(
    super._this_object(orb));
  }


} // class MonitoringStationPOA
