package AssignmentTwo;


/**
* AssignmentTwo/readingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public final class readingsHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.Reading value[] = null;

  public readingsHolder ()
  {
  }

  public readingsHolder (AssignmentTwo.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.readingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.readingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.readingsHelper.type ();
  }

}
