package AssignmentTwo;


/**
* AssignmentTwo/Reading.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class Reading implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;
  public String station_name = null;
  public int reading_level = (int)0;

  public Reading ()
  {
  } // ctor

  public Reading (int _time, int _date, String _station_name, int _reading_level)
  {
    time = _time;
    date = _date;
    station_name = _station_name;
    reading_level = _reading_level;
  } // ctor

} // class Reading
