package AssignmentTwo;


/**
* AssignmentTwo/serverListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class serverListHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.ServerDetails value[] = null;

  public serverListHolder ()
  {
  }

  public serverListHolder (AssignmentTwo.ServerDetails[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.serverListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.serverListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.serverListHelper.type ();
  }

}
