package AssignmentTwo;

/**
* AssignmentTwo/ServerDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public final class ServerDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.ServerDetails value = null;

  public ServerDetailsHolder ()
  {
  }

  public ServerDetailsHolder (AssignmentTwo.ServerDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.ServerDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.ServerDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.ServerDetailsHelper.type ();
  }

}
