package AssignmentTwo;


/**
* AssignmentTwo/stationListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 30 March 2020 15:54:25 o'clock BST
*/

public final class stationListHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.StationDetails value[] = null;

  public stationListHolder ()
  {
  }

  public stationListHolder (AssignmentTwo.StationDetails[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.stationListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.stationListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.stationListHelper.type ();
  }

}
