package AssignmentTwo;

/**
* AssignmentTwo/StationDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Tuesday, 31 March 2020 19:26:32 o'clock BST
*/

public final class StationDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public AssignmentTwo.StationDetails value = null;

  public StationDetailsHolder ()
  {
  }

  public StationDetailsHolder (AssignmentTwo.StationDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssignmentTwo.StationDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssignmentTwo.StationDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssignmentTwo.StationDetailsHelper.type ();
  }

}
