package AssignmentTwo;


/**
* AssignmentTwo/StationDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Monday, 13 April 2020 17:15:40 o'clock BST
*/

public final class StationDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String station_name = null;
  public String location = null;

  public StationDetails ()
  {
  } // ctor

  public StationDetails (String _station_name, String _location)
  {
    station_name = _station_name;
    location = _location;
  } // ctor

} // class StationDetails
