package AssignmentTwo;


/**
* AssignmentTwo/StationDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AssignmentTwo.idl
* Tuesday, 31 March 2020 19:26:32 o'clock BST
*/

public final class StationDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String station_name = null;
  public String location = null;

  public StationDetails ()
  {
  } // ctor

  public StationDetails (String _station_name, String _location)
  {
    station_name = _station_name;
    location = _location;
  } // ctor

} // class StationDetails
