module AssignmentTwo {
    struct Reading {
        long time;
        long date;
        string station_name;
        long reading_level;
    };
    struct StationDetails {
        string station_name;
        string location;
    };
    struct ServerDetails {
        string server_name;
        string location;
    };
    struct Agency {
                string agency_name;
                string agency_region;
                string agency_contact;
            };
    typedef sequence<StationDetails> stationList;
    typedef sequence<ServerDetails> serverList;
    typedef sequence<Reading> readings;
    struct Alert {
        string server_name;
        readings alerts;
    };
    interface MonitoringStation {
        Reading reading();
        readonly attribute readings reading_log;
        void get_reading();
        void set_details(in StationDetails details);
        StationDetails get_details();
        void activate();
        void deactivate();
        void reset();
    };
    interface LocalServer {
        readonly attribute stationList connected_stations;
        ServerDetails get_server_details();
        void set_details(in ServerDetails details);
        readings all_readings();
        readings get_readings(in string station_name);
        readings get_current_readings();
        readings alerts();
        void register_monitoring_station(in StationDetails details);
        void send_alert(in Reading reading);
    };
    interface MonitoringCentre {
        readings all_readings();
        readings get_readings(in string server_name);
        readonly attribute serverList connected_servers;
        void register_local_server(in ServerDetails details);
        void unregister_local_server(in ServerDetails details);
        void send_alert(in Alert alert);
        void register_agency(in Agency agency);
    };
};
